[package]
name = "ukendio/jecs"
version = "0.9.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
include = [
	"default.project.json",
	"src",
	"wally.toml",
	"README.md",
	"CHANGELOG.md",
	"LICENSE",
]
exclude = ["src/mirror.luau"]
