[package]
name = "ukendio/jecs"
version = "0.0.0-prototype.rc.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["default.project.json", "lib", "wally.toml", "README.md"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
Matter = "matter-ecs/matter@0.8.0"
ecr = "centau/ecr@0.8.0"



