[package]
name = "ukendio/jecs"
version = "0.3.0-rc.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src/**",
    "src",
    "wally.toml",
    "README.md",
    "CHANGELOG.md",
]
exclude = ["**"]
